#!/bin/bash
for i in a b c d e f g h i j k l m n o p q r s t u v w x y z
do
  for j in a b c d e f g h i j k l m n o p q r s t u v w x y z
  do
    if [ "$i$j" != "oo" ]
    then
      echo -n "$i$j "
    fi
  done
done
echo